### ISSUE TITLE
Player can still play after being busted.

### ISSUE THREAD

**Issue by prathmeshbankar03** [LaKhWaN/Blackjack#1]
![image](https://user-images.githubusercontent.com/78162039/215272343-7ae047b9-2479-496f-8832-253993233693.png)

If you are busted and you click "STAND" the dealer starts playing and you will get another chance to win 😎😅

**Comment by LaKhWaN** [comment]
Forgot to disable the "STAND" button after getting BUSTED, fixed in the latest update!
Thanks for letting me know.

**Comment by prathmeshbankar03** [comment]
Shish piro people
